const test=require('node:test');const assert=require('node:assert/strict');const fs=require('fs');const path=require('path');const sqlite3=require('sqlite3').verbose();
const {AssessmentAnswer}=require('../src/domain/entities');const{QUESTION_IDS,DASHBOARD_FRAMEWORKS,QUESTION_METADATA}=require('../src/domain/instrument');const ScoringService=require('../src/services/ScoringService');const RedFlagRepository=require('../src/repositories/RedFlagRepository');const RedFlagService=require('../src/services/RedFlagService');const EligibilityService=require('../src/services/EligibilityService');const TokenService=require('../src/services/TokenService');const PasswordService=require('../src/services/PasswordService');const{isPasswordValid}=require('../src/utils/passwordPolicy');
const answers=score=>QUESTION_IDS.map(questionId=>new AssessmentAnswer({assessmentId:'a',questionId,score}));
const open=()=>new Promise((resolve,reject)=>{const db=new sqlite3.Database(':memory:');db.exec(fs.readFileSync(path.join(__dirname,'../db/schema.sql'),'utf8'),e=>e?reject(e):resolve(db));});
test('scoring keeps the real score band and never caps it',()=>{const rows=answers(5);rows.find(a=>a.questionId===17).score=0;const r=new ScoringService().calculate(rows);assert.equal(r.level.id,'A4');assert.ok(r.overallScore>90);assert.equal(r.completion.total,QUESTION_IDS.length);});
test('Stage 2 seeds exactly nine immutable flags and 36 thresholds including Q8 zero',async t=>{const db=await open();t.after(()=>db.close());const repo=new RedFlagRepository(db);const controls=await repo.controls(2);assert.equal(controls.length,9);assert.equal(controls.find(c=>c.question_id===8).minimum_score,0);const count=await repo.get('SELECT count(*) n FROM critical_control_thresholds');assert.equal(count.n,36);});
test('red flags block eligibility while score still allows lower products',async t=>{const db=await open();t.after(()=>db.close());const repo=new RedFlagRepository(db);const rows=answers(5);rows.find(a=>a.questionId===17).score=1;const flags=await new RedFlagService(repo).evaluate(2,rows);assert.equal(flags.length,9);assert.equal(flags.some(f=>f.failed),true);assert.deepEqual(new EligibilityService().products('advanced',flags),[]);assert.deepEqual(new EligibilityService().products('assured',flags.map(f=>({...f,failed:false}))),['aligned-certificate','assured-certificate']);});
test('backend catalog maps canonical questions and frameworks',()=>{assert.equal(Object.keys(QUESTION_METADATA).length,QUESTION_IDS.length);assert.equal(DASHBOARD_FRAMEWORKS.length,7);});
test('password and token primitives remain valid',async()=>{const p=new PasswordService();const hash=await p.hash('Secret1');assert.equal(await p.verify('Secret1',hash),true);assert.equal(isPasswordValid('Secret1'),true);const token=new TokenService('test-secret');assert.equal(token.verify(token.sign({id:'u',companyId:'c'})).sub,'u');});
