PRAGMA foreign_keys = ON;

CREATE TABLE companies (id TEXT PRIMARY KEY, name TEXT UNIQUE NOT NULL COLLATE NOCASE, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE users (id TEXT PRIMARY KEY, company_id TEXT UNIQUE NOT NULL REFERENCES companies(id) ON DELETE CASCADE, email TEXT UNIQUE NOT NULL COLLATE NOCASE, password_hash TEXT NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE ai_systems (id TEXT PRIMARY KEY, company_id TEXT NOT NULL REFERENCES companies(id) ON DELETE CASCADE, name TEXT NOT NULL COLLATE NOCASE, description TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(company_id,name));

CREATE TABLE certificate_levels (id TEXT PRIMARY KEY CHECK(id IN ('aware','aligned','assured','advanced')), code TEXT UNIQUE NOT NULL, name TEXT UNIQUE NOT NULL, description TEXT NOT NULL, score_min INTEGER NOT NULL, score_max INTEGER NOT NULL, rank INTEGER UNIQUE NOT NULL, badge_eligible INTEGER NOT NULL CHECK(badge_eligible IN (0,1)));
CREATE TABLE certificate_products (id TEXT PRIMARY KEY, level_id TEXT REFERENCES certificate_levels(id), code TEXT UNIQUE NOT NULL, product_type TEXT NOT NULL CHECK(product_type IN ('assessment','certificate')), name TEXT UNIQUE NOT NULL, description TEXT NOT NULL, cta_label TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, display_order INTEGER UNIQUE NOT NULL);
CREATE TABLE product_prices (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES certificate_products(id) ON DELETE CASCADE, amount_minor INTEGER NOT NULL, currency TEXT NOT NULL, billing_period TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1, valid_from DATETIME DEFAULT CURRENT_TIMESTAMP, valid_until DATETIME);
CREATE TABLE certificate_product_features (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES certificate_products(id) ON DELETE CASCADE, label TEXT NOT NULL, display_order INTEGER NOT NULL, UNIQUE(product_id,display_order));

INSERT INTO certificate_levels VALUES ('aware','A1','Aware','Internal readiness result; no public certificate.',0,40,1,0),('aligned','A2','Aligned','Entry certificate level.',41,65,2,1),('assured','A3','Assured','Intermediate certificate level.',66,85,3,1),('advanced','A4','Advanced','Highest certificate level.',86,100,4,1);
INSERT INTO certificate_products VALUES ('aligned-certificate','aligned','CERT-ALIGNED','certificate','Aligned Certificate','Available after an eligible evidence dossier.','Open evidence dossier',1,1),('assured-certificate','assured','CERT-ASSURED','certificate','Assured Certificate','Available after an eligible evidence dossier.','Open evidence dossier',1,2),('advanced-certificate','advanced','CERT-ADVANCED','certificate','Advanced Certificate','Available after an eligible evidence dossier.','Open evidence dossier',1,3);
INSERT INTO product_prices VALUES ('price-aligned-eur-annual','aligned-certificate',34900,'EUR','year',1,'2026-01-01',NULL),('price-assured-eur-annual','assured-certificate',64900,'EUR','year',1,'2026-01-01',NULL),('price-advanced-eur-annual','advanced-certificate',119000,'EUR','year',1,'2026-01-01',NULL);
INSERT INTO certificate_product_features VALUES ('f3','aligned-certificate','Evidence dossier and public certificate',1),('f4','assured-certificate','Evidence dossier and public certificate',1),('f5','advanced-certificate','Evidence dossier and public certificate',1);

CREATE TABLE assessments (
 id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, ai_system_id TEXT NOT NULL REFERENCES ai_systems(id),
 adoption_stage INTEGER NOT NULL CHECK(adoption_stage BETWEEN 1 AND 4), status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','finalized')),
 completion_percentage REAL NOT NULL DEFAULT 0, overall_score REAL, result_level_id TEXT REFERENCES certificate_levels(id), remediation_of_assessment_id TEXT REFERENCES assessments(id), completed_at DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX idx_one_active_assessment ON assessments(user_id) WHERE status='draft';
CREATE TABLE assessment_answers (id TEXT PRIMARY KEY, assessment_id TEXT NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, question_id INTEGER NOT NULL CHECK(question_id BETWEEN 1 AND 36), score INTEGER NOT NULL CHECK(score BETWEEN 0 AND 5), evidence TEXT NOT NULL DEFAULT '', attestation TEXT NOT NULL DEFAULT '', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(assessment_id,question_id));
CREATE TABLE domain_scores (id TEXT PRIMARY KEY, assessment_id TEXT NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, domain_name TEXT NOT NULL, score REAL NOT NULL, UNIQUE(assessment_id,domain_name));

CREATE TABLE critical_controls (id TEXT PRIMARY KEY, question_id INTEGER UNIQUE NOT NULL CHECK(question_id BETWEEN 1 AND 36), domain_id TEXT NOT NULL, guidance TEXT NOT NULL);
CREATE TABLE critical_control_thresholds (control_id TEXT NOT NULL REFERENCES critical_controls(id), adoption_stage INTEGER NOT NULL CHECK(adoption_stage BETWEEN 1 AND 4), minimum_score INTEGER NOT NULL CHECK(minimum_score BETWEEN 0 AND 5), PRIMARY KEY(control_id,adoption_stage));
CREATE TABLE assessment_red_flags (id TEXT PRIMARY KEY, assessment_id TEXT NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, control_id TEXT NOT NULL REFERENCES critical_controls(id), question_id INTEGER NOT NULL, actual_score INTEGER NOT NULL, threshold INTEGER NOT NULL, failed INTEGER NOT NULL CHECK(failed IN (0,1)), created_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(assessment_id,control_id));
CREATE TRIGGER red_flags_immutable_update BEFORE UPDATE ON assessment_red_flags BEGIN SELECT RAISE(ABORT,'ASSESSMENT_RED_FLAGS_IMMUTABLE'); END;
CREATE TRIGGER red_flags_immutable_delete BEFORE DELETE ON assessment_red_flags BEGIN SELECT RAISE(ABORT,'ASSESSMENT_RED_FLAGS_IMMUTABLE'); END;

INSERT INTO critical_controls VALUES
 ('value-realisation',8,'revenue','Document how AI value is measured and reviewed.'),('system-inventory',10,'governance','Maintain an owned inventory of every AI system in scope.'),('governance-policy',11,'governance','Approve and communicate an AI governance policy.'),('risk-assessment',16,'risk','Perform proportionate AI risk assessments before deployment.'),('ai-act-readiness',17,'risk','Map applicable EU AI Act duties and accountable owners.'),('high-risk-identification',18,'risk','Classify high-risk and prohibited AI use cases.'),('incident-response',19,'risk','Test an AI incident response and escalation process.'),('personal-data',23,'data','Apply privacy and personal-data controls to AI processing.'),('human-accountability',26,'human','Assign meaningful human oversight and accountability.');
INSERT INTO critical_control_thresholds
SELECT id,1,CASE WHEN question_id=8 THEN 0 ELSE 1 END FROM critical_controls UNION ALL
SELECT id,2,CASE WHEN question_id=8 THEN 0 ELSE 2 END FROM critical_controls UNION ALL
SELECT id,3,CASE WHEN question_id=8 THEN 1 ELSE 3 END FROM critical_controls UNION ALL
SELECT id,4,CASE WHEN question_id=8 THEN 2 ELSE 4 END FROM critical_controls;

CREATE TABLE remediation_confirmations (assessment_id TEXT NOT NULL REFERENCES assessments(id) ON DELETE CASCADE, domain_id TEXT NOT NULL, confirmed INTEGER NOT NULL CHECK(confirmed IN (0,1)), confirmed_at DATETIME, PRIMARY KEY(assessment_id,domain_id));
CREATE TABLE evidence_dossiers (id TEXT PRIMARY KEY, assessment_id TEXT NOT NULL REFERENCES assessments(id), company_id TEXT NOT NULL REFERENCES companies(id), product_id TEXT NOT NULL REFERENCES certificate_products(id), status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','issued')), signatory_name TEXT, declaration_accepted INTEGER NOT NULL DEFAULT 0, signed_at DATETIME, issued_at DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(assessment_id));
CREATE TABLE evidence_items (id TEXT PRIMARY KEY, dossier_id TEXT NOT NULL REFERENCES evidence_dossiers(id) ON DELETE CASCADE, control_id TEXT NOT NULL REFERENCES critical_controls(id), reference TEXT NOT NULL DEFAULT '', attachment_id TEXT, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE(dossier_id,control_id));
CREATE TABLE evidence_attachments (id TEXT PRIMARY KEY, dossier_id TEXT NOT NULL REFERENCES evidence_dossiers(id) ON DELETE CASCADE, item_id TEXT UNIQUE NOT NULL REFERENCES evidence_items(id) ON DELETE CASCADE, original_name TEXT NOT NULL, stored_name TEXT UNIQUE NOT NULL, mime_type TEXT NOT NULL, size INTEGER NOT NULL, sha256 TEXT NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE badges (id TEXT PRIMARY KEY, dossier_id TEXT UNIQUE NOT NULL REFERENCES evidence_dossiers(id), assessment_id TEXT UNIQUE NOT NULL REFERENCES assessments(id), company_id TEXT NOT NULL REFERENCES companies(id), level_id TEXT NOT NULL REFERENCES certificate_levels(id), score REAL NOT NULL, issued_at DATETIME DEFAULT CURRENT_TIMESTAMP, expires_at DATETIME NOT NULL, verification_token TEXT UNIQUE NOT NULL, frameworks_included TEXT);
CREATE TABLE audit_logs (id TEXT PRIMARY KEY, company_id TEXT, user_id TEXT, assessment_id TEXT, action TEXT NOT NULL, details TEXT, ip_address TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX idx_answers_assessment ON assessment_answers(assessment_id); CREATE INDEX idx_flags_assessment ON assessment_red_flags(assessment_id); CREATE INDEX idx_dossiers_company ON evidence_dossiers(company_id); CREATE INDEX idx_badges_company ON badges(company_id);
