const fs=require('fs');const path=require('path');const crypto=require('crypto');const {v4:uuid}=require('uuid');const httpError=require('../utils/httpError');const {FRAMEWORKS}=require('../domain/instrument');
const UPLOAD_DIR=path.join(__dirname,'../../uploads/evidence');
class DossierService{
 constructor(repo,assessments,flags,eligibility,badges){Object.assign(this,{repo,assessments,flags,eligibility,badges});fs.mkdirSync(UPLOAD_DIR,{recursive:true});}
 async create(user,assessmentId,productId){const a=await this.assessments.findById(assessmentId);if(!a||a.userId!==user.id)throw httpError(404,'Assessment not found','ASSESSMENT_NOT_FOUND');if(a.status!=='finalized')throw httpError(409,'Assessment is not finalized','ASSESSMENT_NOT_FINALIZED');const existing=await this.repo.findByAssessment(a.id);if(existing)return this.detail(user.id,existing.id);const flags=await this.flags.byAssessment(a.id);const allowed=this.eligibility.products(a.resultLevelId,flags);if(!allowed.includes(productId))throw httpError(409,'Certificate product is not eligible','CERTIFICATE_PRODUCT_NOT_ELIGIBLE');const controls=await this.flags.controls(a.adoptionStage);const d=await this.repo.create({id:uuid(),assessmentId:a.id,companyId:user.companyId,productId},controls);return this.detail(user.id,d.id);}
 async owned(userId,id){const d=await this.repo.findOwned(id,userId);if(!d)throw httpError(404,'Evidence dossier not found','DOSSIER_NOT_FOUND');return d;}
 async detail(userId,id){const d=await this.owned(userId,id);return{dossier:{id:d.id,assessmentId:d.assessment_id,productId:d.product_id,status:d.status,signatoryName:d.signatory_name,signedAt:d.signed_at,issuedAt:d.issued_at},items:(await this.repo.items(id)).map(i=>({id:i.id,controlId:i.control_id,reference:i.reference,attachment:i.attachment_id?{id:i.attachment_id,name:i.original_name,mimeType:i.mime_type,size:i.size,sha256:i.sha256}:null}))};}
 async saveItem(userId,id,controlId,reference){const d=await this.owned(userId,id);if(d.status!=='draft')throw httpError(409,'Dossier is issued','DOSSIER_ISSUED');const value=String(reference||'').trim();if(!await this.repo.saveItem(id,controlId,value))throw httpError(404,'Evidence item not found','EVIDENCE_ITEM_NOT_FOUND');return this.detail(userId,id);}
 async attach(userId,id,itemId,file){const d=await this.owned(userId,id);if(d.status!=='draft')throw httpError(409,'Dossier is issued','DOSSIER_ISSUED');const item=await this.repo.item(itemId,id);if(!item)throw httpError(404,'Evidence item not found','EVIDENCE_ITEM_NOT_FOUND');const ext=path.extname(file.originalname).toLowerCase();const allowed={'.pdf':'application/pdf','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.docx':'application/vnd.openxmlformats-officedocument.wordprocessingml.document'};if(!allowed[ext]||allowed[ext]!==file.mimetype)throw httpError(415,'Unsupported attachment type','INVALID_ATTACHMENT_TYPE');const storedName=`${uuid()}${ext}`;const target=path.join(UPLOAD_DIR,storedName);fs.writeFileSync(target,file.buffer);const meta={id:uuid(),storedName,originalName:path.basename(file.originalname),mimeType:file.mimetype,size:file.size,sha256:crypto.createHash('sha256').update(file.buffer).digest('hex')};try{const old=await this.repo.attach(item,id,meta);if(old)fs.rmSync(path.join(UPLOAD_DIR,old.stored_name),{force:true});}catch(e){fs.rmSync(target,{force:true});throw e;}return this.detail(userId,id);}
 async removeAttachment(userId,id,itemId){await this.owned(userId,id);const item=await this.repo.item(itemId,id);if(!item)throw httpError(404,'Evidence item not found','EVIDENCE_ITEM_NOT_FOUND');const old=await this.repo.removeAttachment(item);if(old)fs.rmSync(path.join(UPLOAD_DIR,old.stored_name),{force:true});}
 async download(userId,id,itemId){await this.owned(userId,id);const item=await this.repo.item(itemId,id);if(!item?.stored_name)throw httpError(404,'Attachment not found','ATTACHMENT_NOT_FOUND');return{path:path.join(UPLOAD_DIR,item.stored_name),name:item.original_name,mime:item.mime_type};}
 async issue(user,id,input){const d=await this.owned(user.id,id);if(d.status==='issued'){return this.detail(user.id,id);}const items=await this.repo.items(id);if(items.length!==9||items.some(i=>!String(i.reference).trim()))throw httpError(409,'All nine evidence references are required','EVIDENCE_INCOMPLETE');const signatory=String(input.signatoryName||'').trim().replace(/\s+/g,' ');if(!signatory||input.acceptedDeclaration!==true)throw httpError(400,'Signature and declaration are required','SIGNATURE_REQUIRED');await this.repo.issue(id,signatory);const a=await this.assessments.findById(d.assessment_id);const level=d.product_id.replace('-certificate','');await this.badges.issueBadge(a.id,user.companyId,level,a.overallScore,FRAMEWORKS,id);return this.detail(user.id,id);}
}
DossierService.UPLOAD_DIR=UPLOAD_DIR;module.exports=DossierService;
